author: Your Name
description: An academic web CV
logo: /assets/img/logo.png
google_analytics: ''
github_username: ngpaladi
cv: /assets/img/logo.png
linkedin: https://www.linkedin.com/in/noahpaladino
twitter: https://twitter.com/noahpaladino
google_scholar: 'https://scholar.google.com/citations?user=iocpnRQAAAAJ'
